services:
  - type: web
    name: meesho-label-downloader
    env: node
    plan: free
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: MEESHO_EMAIL
        sync: false
      - key: MEESHO_PASSWORD
        sync: false
      - key: LABEL_DOWNLOADED_FILTER
        sync: false
      - key: API_KEY
        generateValue: true
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
