services:
  - type: web
    name: meesho-label-downloader
    env: docker
    plan: free
    envVars:
      - key: MEESHO_EMAIL
        sync: false
      - key: MEESHO_PASSWORD
        sync: false
      - key: LABEL_DOWNLOADED_FILTER
        sync: false
      - key: API_KEY
        generateValue: true
